import nodeMailer from "nodemailer";
import "dotenv/config";
import { asyncHandler } from "./AsyncHandler.utility.js";
import { response } from "express";


/**
 * import the sendMail() method and then user..... Firt is the email and second is the code....
 * 
 * Email sending code...
 * await sendMail("bishalbhat3313@gmail.com", 498742)
 */


// Create transporter - It will be used to send emails....
const transporter = nodeMailer.createTransport({
  host: process.env.HOST,
  port: Number(process.env.PORT),
  secure: true, // true for 465, false for 587
  auth: {
    user: process.env.EMAIL,
    pass: process.env.PASS, // App password... We dont use original email password here. Instead, we generate app password and use that here....
  },
});


// Method to send emails...
export const sendMail = async (to, code) => {
  const HTMLMessage = `
          <!DOCTYPE html>
          <html lang="en">
          <body style="margin:0; padding:0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f5f5f5;">
          <div style="width:100%; padding:20px 0; text-align:center; background-color:#f5f5f5;">
          <div style="max-width:500px; margin:0 auto; background-color:#ffffff; border-radius:10px; padding:40px 20px; box-shadow:0 4px 10px rgba(0,0,0,0.1);">
               
               <!-- Header -->
               <div style="font-size:26px; font-weight:bold; color:#1a73e8; margin-bottom:20px;">
               FWU Sathi Verification Code
               </div>
               
               <!-- Subtext -->
               <div style="font-size:16px; color:#555555; margin-bottom:30px;">
               Please use the following 6-digit code to verify your email:
               </div>
               
               <!-- Verification Code (single line) -->
               <div style="font-size:40px; font-weight:bold; color:#6d65fc; letter-spacing:8px;">
               ${code}
               </div>
               
               <!-- Footer -->
               <div style="margin-top:30px; font-size:14px; color:#999999;">
               If you did not request this code, please ignore this email.
               </div>

          </div>
          </div>
          </body>
          </html>
     `;

     const subject = "Email Verification - FWU Sathi"

  try {
    const info = await transporter.sendMail({
      to,
      from: `"FWU Sathi" <${process.env.EMAIL}>`,
      subject,
      html: HTMLMessage,
    });

    // return success info
    return {
      success: true,                // Boolean indicating if the email was successfully sent or not.
      messageId: info.messageId,    // Unique identifier for the email generated by the SMTP server
      accepted: info.accepted,      // Array of recipient email addresses that were successfully accepted by the server
      rejected: info.rejected,      // Array of recipient email addresses that were rejected by the server
      response: info.response,      // Raw response string from the SMTP server confirming the sending status
    };
    console.log("Email send successfully.")
    
  } catch (error) {
    console.log("Email send Failed: ", error.message);

    // return failure info incase the email is not send ..
    return {
      success: false,
      error: error.message,
    };
  }

  console.log(info);
};
